Parameters:
  DBInstanceName:
    Type: String
    Description: The name of the RDS DB instance
    Default: my-rds-instance
  DBInstanceClass:
    Type: String
    Description: The instance class for the RDS DB instance
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
  DBName:
    Type: String
    Description: The name of the initial database
    Default: mydb
  DBUsername:
    Type: String
    Description: The username for the initial database user
    Default: admin
  DBPassword:
    Type: String
    Description: The password for the initial database user
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC to launch the RDS instance in
  RDSSecurityGroupName:
    Type: String
    Description: The name of the new security group for the RDS instance
    Default: MyRDSSecurityGroup

Resources:
  MyRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: '12.7'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      StorageType: gp2
      MultiAZ: false
      VPCSecurityGroups:
        - !Ref MyRDSSecurityGroup

Outputs:
  RDSSecurityGroupId:
    Value: !Ref MyRDSSecurityGroup
    Description: The ID of the new security group for the RDS instance
